-- Editable server channel groups (categories) per channel type.

create table if not exists public.channel_categories (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  server_id bigint not null references public.servers (id) on delete cascade,
  name text not null,
  channel_type text not null default 'text',
  position integer not null default 0,
  constraint channel_categories_name_not_blank check (char_length(trim(name)) > 0),
  constraint channel_categories_type_check check (
    channel_type in ('text', 'voice', 'forum')
  )
);

create index if not exists channel_categories_server_position_idx
  on public.channel_categories (server_id, channel_type, position, id);

alter table public.channels
  add column if not exists category_id bigint references public.channel_categories (id) on delete set null;

create index if not exists channels_category_id_idx
  on public.channels (category_id);

alter table public.channel_categories enable row level security;

create or replace function public.normalize_channel_type(p_type text)
returns text
language sql
immutable
as $$
  select case
    when lower(trim(coalesce(p_type, ''))) in ('voice', 'forum') then lower(trim(p_type))
    else 'text'
  end;
$$;

create or replace function public.ensure_default_channel_categories(p_server_id bigint)
returns void
language plpgsql
security definer
set search_path to public
as $$
begin
  if not exists (
    select 1
    from public.channel_categories cc
    where cc.server_id = p_server_id
      and cc.channel_type = 'text'
  ) then
    insert into public.channel_categories (server_id, name, channel_type, position)
    values (p_server_id, 'TEXT CHANNELS', 'text', 0);
  end if;

  if not exists (
    select 1
    from public.channel_categories cc
    where cc.server_id = p_server_id
      and cc.channel_type = 'voice'
  ) then
    insert into public.channel_categories (server_id, name, channel_type, position)
    values (p_server_id, 'VOICE CHANNELS', 'voice', 1);
  end if;

  if not exists (
    select 1
    from public.channel_categories cc
    where cc.server_id = p_server_id
      and cc.channel_type = 'forum'
  ) then
    insert into public.channel_categories (server_id, name, channel_type, position)
    values (p_server_id, 'FORUM CHANNELS', 'forum', 2);
  end if;
end;
$$;

create or replace function public.default_channel_category_id(
  p_server_id bigint,
  p_channel_type text
)
returns bigint
language sql
stable
security definer
set search_path to public
as $$
  select cc.id
  from public.channel_categories cc
  where cc.server_id = p_server_id
    and cc.channel_type = public.normalize_channel_type(p_channel_type)
  order by cc.position asc, cc.id asc
  limit 1;
$$;

create or replace function public.get_server_channel_categories(p_server_id bigint)
returns table (
  id bigint,
  server_id bigint,
  name text,
  channel_type text,
  "position" integer,
  created_at timestamptz
)
language plpgsql
stable
security definer
set search_path to public
as $$
begin
  if auth.uid() is null then
    return;
  end if;

  if not exists (
    select 1
    from public.server_members sm
    where sm.server_id = p_server_id
      and sm.user_id = auth.uid()
  )
  and not exists (
    select 1
    from public.servers s
    where s.id = p_server_id
      and coalesce(s.visibility, 'public') = 'public'
  ) then
    return;
  end if;

  perform public.ensure_default_channel_categories(p_server_id);

  return query
  select
    cc.id,
    cc.server_id,
    cc.name,
    cc.channel_type,
    cc.position,
    cc.created_at
  from public.channel_categories cc
  where cc.server_id = p_server_id
  order by cc.position asc, cc.id asc;
end;
$$;

create or replace function public.manage_channel_category(
  p_server_id bigint,
  p_name text,
  p_channel_type text default 'text',
  p_position integer default null,
  p_category_id bigint default null,
  p_delete boolean default false
)
returns public.channel_categories
language plpgsql
security definer
set search_path to public
as $$
declare
  category_row public.channel_categories;
  normalized_type text := public.normalize_channel_type(p_channel_type);
  fallback_category_id bigint;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  if not public.user_can_manage_channels(p_server_id, auth.uid()) then
    raise exception 'You do not have permission to manage channel groups';
  end if;

  perform public.ensure_default_channel_categories(p_server_id);

  if p_delete then
    if p_category_id is null then
      raise exception 'Category id required';
    end if;

    select cc.*
    into category_row
    from public.channel_categories cc
    where cc.id = p_category_id
      and cc.server_id = p_server_id;

    if category_row.id is null then
      raise exception 'Channel group not found';
    end if;

    fallback_category_id := public.default_channel_category_id(
      p_server_id,
      category_row.channel_type
    );

    if fallback_category_id = category_row.id then
      raise exception 'Cannot delete the last channel group for this type';
    end if;

    update public.channels
    set category_id = fallback_category_id
    where category_id = category_row.id;

    delete from public.channel_categories
    where id = category_row.id;

    return category_row;
  end if;

  if p_category_id is null then
    insert into public.channel_categories (
      server_id,
      name,
      channel_type,
      position
    )
    values (
      p_server_id,
      trim(p_name),
      normalized_type,
      coalesce(
        p_position,
        (
          select coalesce(max(cc.position), -1) + 1
          from public.channel_categories cc
          where cc.server_id = p_server_id
            and cc.channel_type = normalized_type
        )
      )
    )
    returning * into category_row;
  else
    update public.channel_categories
    set
      name = trim(p_name),
      channel_type = normalized_type,
      position = coalesce(p_position, position)
    where id = p_category_id
      and server_id = p_server_id
    returning * into category_row;

    if category_row.id is null then
      raise exception 'Channel group not found';
    end if;
  end if;

  return category_row;
end;
$$;

drop function if exists public.get_accessible_server_channels(bigint);

create or replace function public.get_accessible_server_channels(p_server_id bigint)
returns table (
  id bigint,
  server_id bigint,
  name text,
  type text,
  "position" integer,
  created_at timestamptz,
  tier_id bigint,
  category_id bigint,
  required_tier_name text,
  can_access boolean
)
language plpgsql
stable
security definer
set search_path to public
as $$
begin
  perform public.ensure_default_channel_categories(p_server_id);

  update public.channels c
  set category_id = public.default_channel_category_id(
    c.server_id,
    c.type
  )
  where c.server_id = p_server_id
    and c.category_id is null;

  return query
  select
    c.id,
    c.server_id,
    c.name,
    c.type,
    c.position as "position",
    c.created_at,
    c.tier_id,
    c.category_id,
    st.name as required_tier_name,
    public.user_can_access_channel(c.id, auth.uid()) as can_access
  from public.channels c
  left join public.subscription_tiers st
    on st.id = c.tier_id
  where c.server_id = p_server_id
    and public.user_can_view_channel(c.id, auth.uid())
  order by c.position asc, c.created_at asc;
end;
$$;

drop function if exists public.manage_server_channel(
  bigint,
  text,
  text,
  integer,
  bigint,
  bigint
);

create or replace function public.manage_server_channel(
  p_server_id bigint,
  p_name text,
  p_type text default 'text',
  p_position integer default null,
  p_tier_id bigint default null,
  p_channel_id bigint default null,
  p_category_id bigint default null
)
returns public.channels
language plpgsql
security definer
set search_path to public
as $$
declare
  channel_row public.channels;
  normalized_type text := public.normalize_channel_type(p_type);
  resolved_category_id bigint;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  if not public.user_can_manage_channels(p_server_id, auth.uid()) then
    raise exception 'You do not have permission to manage channels';
  end if;

  perform public.ensure_default_channel_categories(p_server_id);

  if p_tier_id is not null and not exists (
    select 1
    from public.subscription_tiers st
    where st.id = p_tier_id
      and st.server_id = p_server_id
  ) then
    raise exception 'Tier does not belong to this server';
  end if;

  resolved_category_id := p_category_id;
  if resolved_category_id is not null and not exists (
    select 1
    from public.channel_categories cc
    where cc.id = resolved_category_id
      and cc.server_id = p_server_id
      and cc.channel_type = normalized_type
  ) then
    raise exception 'Channel group does not belong to this server or type';
  end if;

  if resolved_category_id is null then
    resolved_category_id := public.default_channel_category_id(
      p_server_id,
      normalized_type
    );
  end if;

  if p_channel_id is null then
    insert into public.channels (
      server_id,
      name,
      type,
      position,
      tier_id,
      category_id
    )
    values (
      p_server_id,
      p_name,
      normalized_type,
      coalesce(p_position, 0),
      p_tier_id,
      resolved_category_id
    )
    returning * into channel_row;
  else
    update public.channels
    set
      name = p_name,
      type = normalized_type,
      position = coalesce(p_position, position),
      tier_id = p_tier_id,
      category_id = coalesce(resolved_category_id, category_id)
    where id = p_channel_id
      and server_id = p_server_id
    returning * into channel_row;

    if channel_row.id is null then
      raise exception 'Channel not found';
    end if;
  end if;

  return channel_row;
end;
$$;

create or replace function public.user_can_manage_channels_for_server(p_server_id bigint)
returns boolean
language sql
stable
security definer
set search_path to public
as $$
  select public.user_can_manage_channels(p_server_id, auth.uid());
$$;

drop policy if exists "Server members can read channel categories" on public.channel_categories;
create policy "Server members can read channel categories"
on public.channel_categories
for select
to authenticated
using (
  exists (
    select 1
    from public.server_members sm
    where sm.server_id = channel_categories.server_id
      and sm.user_id = auth.uid()
  )
  or exists (
    select 1
    from public.servers s
    where s.id = channel_categories.server_id
      and coalesce(s.visibility, 'public') = 'public'
  )
);

drop policy if exists "Managers can insert channel categories" on public.channel_categories;
create policy "Managers can insert channel categories"
on public.channel_categories
for insert
to authenticated
with check (public.user_can_manage_channels(server_id, auth.uid()));

drop policy if exists "Managers can update channel categories" on public.channel_categories;
create policy "Managers can update channel categories"
on public.channel_categories
for update
to authenticated
using (public.user_can_manage_channels(server_id, auth.uid()))
with check (public.user_can_manage_channels(server_id, auth.uid()));

drop policy if exists "Managers can delete channel categories" on public.channel_categories;
create policy "Managers can delete channel categories"
on public.channel_categories
for delete
to authenticated
using (public.user_can_manage_channels(server_id, auth.uid()));

alter publication supabase_realtime add table public.channel_categories;

select public.ensure_default_channel_categories(s.id)
from public.servers s;

update public.channels c
set category_id = public.default_channel_category_id(c.server_id, c.type)
where c.category_id is null;

grant execute on function public.get_server_channel_categories(bigint) to authenticated;
grant execute on function public.manage_channel_category(bigint, text, text, integer, bigint, boolean) to authenticated;
grant execute on function public.user_can_manage_channels_for_server(bigint) to authenticated;
grant execute on function public.manage_server_channel(bigint, text, text, integer, bigint, bigint, bigint) to authenticated;
