create extension if not exists pgcrypto;

create table if not exists public.mls_groups (
  id bigint generated by default as identity primary key,
  group_identifier uuid not null default gen_random_uuid() unique,
  conversation_kind text not null,
  server_id bigint references public.servers (id) on delete cascade,
  channel_id bigint references public.channels (id) on delete cascade,
  dm_user_a uuid references auth.users (id) on delete cascade,
  dm_user_b uuid references auth.users (id) on delete cascade,
  creator_device_id bigint references public.user_devices (id) on delete set null,
  cipher_suite text not null,
  current_epoch bigint not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint mls_groups_conversation_kind_check
    check (conversation_kind in ('dm', 'channel', 'server_channel')),
  constraint mls_groups_target_check
    check (
      (conversation_kind in ('channel', 'server_channel') and channel_id is not null)
      or (conversation_kind = 'dm' and dm_user_a is not null and dm_user_b is not null)
    )
);

create index if not exists mls_groups_channel_id_idx
  on public.mls_groups (channel_id);

create index if not exists mls_groups_dm_users_idx
  on public.mls_groups (dm_user_a, dm_user_b);

do $$
begin
  if exists (
    select 1
    from pg_proc
    where proname = 'set_updated_at'
      and pronamespace = 'public'::regnamespace
  ) and not exists (
    select 1
    from pg_trigger
    where tgname = 'set_mls_groups_updated_at'
  ) then
    create trigger set_mls_groups_updated_at
    before update on public.mls_groups
    for each row
    execute function public.set_updated_at();
  end if;
end;
$$;

create table if not exists public.mls_key_packages (
  id bigint generated by default as identity primary key,
  user_device_id bigint not null references public.user_devices (id) on delete cascade,
  key_package_ref uuid not null default gen_random_uuid() unique,
  cipher_suite text not null,
  credential_type text not null default 'basic',
  credential_identity text not null,
  key_package text not null,
  signature_public_key text,
  hpke_public_key text,
  leaf_node text,
  is_consumed boolean not null default false,
  consumed_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  expires_at timestamptz,
  constraint mls_key_packages_consumed_requires_timestamp_check
    check (
      (is_consumed = false and consumed_at is null)
      or (is_consumed = true and consumed_at is not null)
    )
);

create index if not exists mls_key_packages_user_device_id_idx
  on public.mls_key_packages (user_device_id, created_at desc);

create index if not exists mls_key_packages_available_idx
  on public.mls_key_packages (user_device_id, created_at desc)
  where is_consumed = false;

create table if not exists public.mls_group_members (
  id bigint generated by default as identity primary key,
  mls_group_id bigint not null references public.mls_groups (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  user_device_id bigint not null references public.user_devices (id) on delete cascade,
  leaf_index integer,
  credential_identity text,
  joined_at_epoch bigint not null default 0,
  removed_at_epoch bigint,
  membership_status text not null default 'active',
  added_by_device_id bigint references public.user_devices (id) on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint mls_group_members_membership_status_check
    check (membership_status in ('pending', 'active', 'removed')),
  unique (mls_group_id, user_device_id)
);

create index if not exists mls_group_members_group_idx
  on public.mls_group_members (mls_group_id, membership_status);

create index if not exists mls_group_members_user_idx
  on public.mls_group_members (user_id, user_device_id);

do $$
begin
  if exists (
    select 1
    from pg_proc
    where proname = 'set_updated_at'
      and pronamespace = 'public'::regnamespace
  ) and not exists (
    select 1
    from pg_trigger
    where tgname = 'set_mls_group_members_updated_at'
  ) then
    create trigger set_mls_group_members_updated_at
    before update on public.mls_group_members
    for each row
    execute function public.set_updated_at();
  end if;
end;
$$;

create table if not exists public.mls_commits (
  id bigint generated by default as identity primary key,
  mls_group_id bigint not null references public.mls_groups (id) on delete cascade,
  epoch bigint not null,
  sender_device_id bigint references public.user_devices (id) on delete set null,
  commit_type text not null,
  commit_message text not null,
  welcome_message text,
  group_info_message text,
  created_at timestamptz not null default timezone('utc', now()),
  constraint mls_commits_commit_type_check
    check (commit_type in ('create', 'add', 'remove', 'update', 'rekey', 'application'))
);

create index if not exists mls_commits_group_epoch_idx
  on public.mls_commits (mls_group_id, epoch desc);

alter table public.messages
  add column if not exists sender_device_id bigint references public.user_devices (id) on delete set null,
  add column if not exists mls_group_id bigint references public.mls_groups (id) on delete set null,
  add column if not exists mls_epoch bigint,
  add column if not exists mls_message_type text,
  add column if not exists mls_wire_format text,
  add column if not exists mls_content_type text,
  add column if not exists mls_authenticated_data jsonb,
  add column if not exists mls_message jsonb;

create index if not exists messages_mls_group_id_idx
  on public.messages (mls_group_id, created_at);

alter table public.direct_messages
  add column if not exists sender_device_id bigint references public.user_devices (id) on delete set null,
  add column if not exists recipient_device_id bigint references public.user_devices (id) on delete set null,
  add column if not exists mls_group_id bigint references public.mls_groups (id) on delete set null,
  add column if not exists mls_epoch bigint,
  add column if not exists mls_message_type text,
  add column if not exists mls_wire_format text,
  add column if not exists mls_content_type text,
  add column if not exists mls_authenticated_data jsonb,
  add column if not exists mls_message jsonb;

create index if not exists direct_messages_mls_group_id_idx
  on public.direct_messages (mls_group_id, created_at);

alter table public.mls_groups enable row level security;
alter table public.mls_key_packages enable row level security;
alter table public.mls_group_members enable row level security;
alter table public.mls_commits enable row level security;

create policy "Users can read MLS groups they belong to"
on public.mls_groups
for select
to authenticated
using (
  exists (
    select 1
    from public.mls_group_members mgm
    where mgm.mls_group_id = public.mls_groups.id
      and mgm.user_id = auth.uid()
  )
);

create policy "Users can create MLS groups from their own devices"
on public.mls_groups
for insert
to authenticated
with check (
  creator_device_id is null
  or exists (
    select 1
    from public.user_devices ud
    where ud.id = creator_device_id
      and ud.user_id = auth.uid()
      and ud.is_active = true
  )
);

create policy "Group members can update MLS groups"
on public.mls_groups
for update
to authenticated
using (
  exists (
    select 1
    from public.mls_group_members mgm
    where mgm.mls_group_id = public.mls_groups.id
      and mgm.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.mls_group_members mgm
    where mgm.mls_group_id = public.mls_groups.id
      and mgm.user_id = auth.uid()
  )
);

create policy "Owners can read their MLS key packages"
on public.mls_key_packages
for select
to authenticated
using (
  exists (
    select 1
    from public.user_devices ud
    where ud.id = user_device_id
      and ud.user_id = auth.uid()
  )
);

create policy "Authenticated users can read available MLS key packages"
on public.mls_key_packages
for select
to authenticated
using (
  is_consumed = false
  and exists (
    select 1
    from public.user_devices ud
    where ud.id = user_device_id
      and ud.is_active = true
  )
);

create policy "Owners can insert their MLS key packages"
on public.mls_key_packages
for insert
to authenticated
with check (
  exists (
    select 1
    from public.user_devices ud
    where ud.id = user_device_id
      and ud.user_id = auth.uid()
      and ud.is_active = true
  )
);

create policy "Owners can update their MLS key packages"
on public.mls_key_packages
for update
to authenticated
using (
  exists (
    select 1
    from public.user_devices ud
    where ud.id = user_device_id
      and ud.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.user_devices ud
    where ud.id = user_device_id
      and ud.user_id = auth.uid()
  )
);

create policy "Users can read MLS group members for their groups"
on public.mls_group_members
for select
to authenticated
using (
  exists (
    select 1
    from public.mls_group_members self
    where self.mls_group_id = public.mls_group_members.mls_group_id
      and self.user_id = auth.uid()
  )
);

create policy "Users can add MLS memberships from their own devices"
on public.mls_group_members
for insert
to authenticated
with check (
  exists (
    select 1
    from public.user_devices ud
    where ud.id = user_device_id
      and ud.user_id = user_id
  )
  and exists (
    select 1
    from public.user_devices ad
    where ad.id = added_by_device_id
      and ad.user_id = auth.uid()
  )
);

create policy "Users can update MLS memberships in their groups"
on public.mls_group_members
for update
to authenticated
using (
  exists (
    select 1
    from public.mls_group_members self
    where self.mls_group_id = public.mls_group_members.mls_group_id
      and self.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.mls_group_members self
    where self.mls_group_id = public.mls_group_members.mls_group_id
      and self.user_id = auth.uid()
  )
);

create policy "Users can read MLS commits for their groups"
on public.mls_commits
for select
to authenticated
using (
  exists (
    select 1
    from public.mls_group_members mgm
    where mgm.mls_group_id = public.mls_commits.mls_group_id
      and mgm.user_id = auth.uid()
  )
);

create policy "Users can insert MLS commits from their own devices"
on public.mls_commits
for insert
to authenticated
with check (
  exists (
    select 1
    from public.mls_group_members mgm
    join public.user_devices ud on ud.id = public.mls_commits.sender_device_id
    where mgm.mls_group_id = public.mls_commits.mls_group_id
      and mgm.user_id = auth.uid()
      and ud.user_id = auth.uid()
  )
);
