-- Foundational public schema baseline.
-- This restores the core tables that later migrations already assume exist.
-- It is intentionally limited to app-owned public objects, not auth/storage internals.

create extension if not exists pgcrypto;

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  email text,
  username text,
  avatar_url text,
  auth_id uuid references auth.users(id) on delete cascade,
  display_name text,
  username_updated_at timestamptz,
  bio text default ''::text,
  last_seen timestamptz default now(),
  presence text default 'online'::text,
  constraint users_auth_id_key unique (auth_id),
  constraint users_username_unique unique (username),
  constraint users_presence_check check (presence in ('online', 'idle', 'dnd', 'invisible'))
);

create table if not exists public.friendships (
  id bigint generated always as identity primary key,
  requester_id uuid not null references auth.users(id) on delete cascade,
  recipient_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'pending',
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  constraint friendships_requester_id_recipient_id_key unique (requester_id, recipient_id),
  constraint friendships_status_check check (status in ('pending', 'accepted', 'blocked'))
);

create table if not exists public.servers (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  owner_id uuid references auth.users(id) on delete set null,
  icon_url text,
  description text,
  price numeric default 0,
  category text default 'other',
  rules text,
  welcome_message text,
  server_type text default 'stone',
  visibility text default 'public',
  member_limit integer,
  invite_code text,
  monetization_enabled boolean default false,
  subscription_price numeric default 0,
  handle text not null,
  display_name text not null,
  constraint servers_handle_key unique (handle),
  constraint servers_invite_code_key unique (invite_code),
  constraint servers_handle_format check (handle ~ '^[a-z0-9_]{3,32}$'),
  constraint servers_visibility_check check (visibility in ('public', 'private'))
);

create table if not exists public.subscription_tiers (
  id bigint generated always as identity primary key,
  server_id bigint not null references public.servers(id) on delete cascade,
  name text not null,
  price numeric not null default 0,
  description text,
  perks text[],
  position integer default 0,
  created_at timestamptz default now()
);

create table if not exists public.channels (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  server_id bigint references public.servers(id) on delete cascade,
  name text,
  type text,
  tier_id bigint references public.subscription_tiers(id) on delete set null,
  position integer default 0
);

create table if not exists public.server_roles (
  id bigint generated always as identity primary key,
  server_id bigint not null references public.servers(id) on delete cascade,
  name text not null,
  color text default '#999999',
  permissions jsonb default '{}'::jsonb,
  position integer default 0,
  is_default boolean default false,
  created_at timestamptz default now()
);

create table if not exists public.server_members (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  server_id bigint references public.servers(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  role text,
  role_id bigint references public.server_roles(id) on delete set null,
  constraint server_members_server_id_user_id_key unique (server_id, user_id)
);

create table if not exists public.server_nicknames (
  id bigint generated always as identity primary key,
  server_id bigint not null references public.servers(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  nickname text not null,
  created_at timestamptz default now(),
  constraint server_nicknames_server_id_user_id_key unique (server_id, user_id)
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  channel_id bigint references public.channels(id) on delete cascade,
  sender_id uuid references auth.users(id) on delete set null,
  ciphertext text,
  msg_packet text,
  sender_device_id bigint
);

create table if not exists public.direct_messages (
  id bigint generated always as identity primary key,
  created_at timestamptz default now(),
  sender_id uuid references auth.users(id) on delete set null,
  recipient_id uuid references auth.users(id) on delete set null,
  ciphertext text not null,
  sender_device_id bigint,
  recipient_device_id bigint
);

create table if not exists public.reports (
  id uuid primary key default gen_random_uuid(),
  reporter_id uuid not null references auth.users(id) on delete cascade,
  reported_user_id uuid references auth.users(id) on delete set null,
  message_id text,
  server_id text,
  reason text not null,
  created_at timestamptz not null default now()
);
