drop policy "Users can insert MLS commits from their own devices" on "public"."mls_commits";

drop policy "Users can read MLS commits for their groups" on "public"."mls_commits";

drop policy "Users can read MLS group members for their groups" on "public"."mls_group_members";

drop policy "Users can update MLS memberships in their groups" on "public"."mls_group_members";

drop policy "Group members can update MLS groups" on "public"."mls_groups";

drop policy "Users can read MLS groups they belong to" on "public"."mls_groups";

drop policy "Servers visible based on visibility" on "public"."servers";

alter table "public"."server_members" drop constraint "server_members_server_id_user_id_key";

alter table "public"."channels" drop constraint "channels_tier_id_fkey";

alter table "public"."direct_messages" drop constraint "direct_messages_recipient_id_fkey";

alter table "public"."direct_messages" drop constraint "direct_messages_sender_id_fkey";

alter table "public"."messages" drop constraint "messages_sender_id_fkey";

alter table "public"."server_members" drop constraint "server_members_role_id_fkey";

alter table "public"."server_members" drop constraint "server_members_user_id_fkey";

alter table "public"."server_nicknames" drop constraint "server_nicknames_user_id_fkey";

drop index if exists "public"."server_members_server_id_user_id_key";

alter table "public"."channel_read_state"
drop constraint if exists "channel_read_state_user_id_channel_id_key";

drop index if exists "public"."channel_read_state_user_id_channel_id_key";


  create table "public"."mls_channel_state_snapshots" (
    "id" bigint generated by default as identity not null,
    "mls_group_id" bigint not null,
    "channel_id" bigint not null,
    "server_id" bigint not null,
    "group_identifier" uuid not null,
    "current_epoch" bigint not null default 0,
    "state_version" bigint not null default 1,
    "client_state" jsonb not null,
    "group_state" jsonb not null,
    "snapshot_payload" jsonb,
    "updated_by_user_id" uuid,
    "updated_by_device_id" bigint,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "updated_at" timestamp with time zone not null default timezone('utc'::text, now())
      );


alter table "public"."mls_channel_state_snapshots" enable row level security;


  create table "public"."post_comment_votes" (
    "id" uuid not null default gen_random_uuid(),
    "comment_id" uuid not null,
    "user_id" uuid not null,
    "vote_type" text not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."post_comment_votes" enable row level security;


  create table "public"."user_settings" (
    "id" bigint generated always as identity not null,
    "user_id" uuid not null,
    "dm_privacy" text not null default 'everyone'::text,
    "created_at" timestamp with time zone default now(),
    "presence" text default 'online'::text
      );


alter table "public"."user_settings" enable row level security;

alter table "public"."channel_read_state" alter column "channel_id" set data type bigint using "channel_id"::bigint;

alter table "public"."channels" enable row level security;

alter table "public"."direct_messages" enable row level security;

alter table "public"."friendships" enable row level security;

alter table "public"."messages" alter column "sender_id" set default gen_random_uuid();

alter table "public"."messages" enable row level security;

alter table "public"."reports" enable row level security;

alter table "public"."server_members" alter column "user_id" set default gen_random_uuid();

alter table "public"."server_members" enable row level security;

alter table "public"."server_nicknames" enable row level security;

alter table "public"."server_roles" enable row level security;

alter table "public"."servers" alter column "owner_id" set default gen_random_uuid();

alter table "public"."servers" enable row level security;

alter table "public"."subscription_tiers" enable row level security;

alter table "public"."users" enable row level security;

CREATE UNIQUE INDEX mls_channel_state_snapshots_channel_id_uidx ON public.mls_channel_state_snapshots USING btree (channel_id);

CREATE UNIQUE INDEX mls_channel_state_snapshots_channel_unique ON public.mls_channel_state_snapshots USING btree (channel_id);

CREATE INDEX mls_channel_state_snapshots_group_identifier_idx ON public.mls_channel_state_snapshots USING btree (group_identifier);

CREATE INDEX mls_channel_state_snapshots_group_idx ON public.mls_channel_state_snapshots USING btree (mls_group_id);

CREATE UNIQUE INDEX mls_channel_state_snapshots_group_unique ON public.mls_channel_state_snapshots USING btree (mls_group_id);

CREATE UNIQUE INDEX mls_channel_state_snapshots_pkey ON public.mls_channel_state_snapshots USING btree (id);

CREATE INDEX mls_channel_state_snapshots_server_idx ON public.mls_channel_state_snapshots USING btree (server_id, updated_at DESC);

CREATE UNIQUE INDEX mls_groups_channel_id_uidx ON public.mls_groups USING btree (channel_id);

CREATE INDEX post_comment_votes_comment_id_idx ON public.post_comment_votes USING btree (comment_id);

CREATE UNIQUE INDEX post_comment_votes_comment_id_user_id_key ON public.post_comment_votes USING btree (comment_id, user_id);

CREATE UNIQUE INDEX post_comment_votes_pkey ON public.post_comment_votes USING btree (id);

CREATE INDEX post_comment_votes_user_id_idx ON public.post_comment_votes USING btree (user_id);

CREATE UNIQUE INDEX server_members_server_id_user_id_uidx ON public.server_members USING btree (server_id, user_id);

CREATE UNIQUE INDEX server_members_server_user_uidx ON public.server_members USING btree (server_id, user_id);

CREATE UNIQUE INDEX unique_friendship_pair ON public.friendships USING btree (LEAST(requester_id, recipient_id), GREATEST(requester_id, recipient_id)) WHERE (status <> 'blocked'::text);

CREATE UNIQUE INDEX user_settings_pkey ON public.user_settings USING btree (id);

CREATE UNIQUE INDEX user_settings_user_id_key ON public.user_settings USING btree (user_id);

CREATE UNIQUE INDEX channel_read_state_user_id_channel_id_key ON public.channel_read_state USING btree (user_id, channel_id);

alter table "public"."mls_channel_state_snapshots" add constraint "mls_channel_state_snapshots_pkey" PRIMARY KEY using index "mls_channel_state_snapshots_pkey";

alter table "public"."post_comment_votes" add constraint "post_comment_votes_pkey" PRIMARY KEY using index "post_comment_votes_pkey";

alter table "public"."user_settings" add constraint "user_settings_pkey" PRIMARY KEY using index "user_settings_pkey";

alter table "public"."channel_read_state" add constraint "channel_read_state_channel_id_fkey" FOREIGN KEY (channel_id) REFERENCES public.channels(id) ON DELETE CASCADE not valid;

alter table "public"."channel_read_state" validate constraint "channel_read_state_channel_id_fkey";

alter table "public"."direct_messages" add constraint "direct_messages_recipient_device_id_fkey" FOREIGN KEY (recipient_device_id) REFERENCES public.user_devices(id) ON DELETE SET NULL not valid;

alter table "public"."direct_messages" validate constraint "direct_messages_recipient_device_id_fkey";

alter table "public"."direct_messages" add constraint "direct_messages_sender_device_id_fkey" FOREIGN KEY (sender_device_id) REFERENCES public.user_devices(id) ON DELETE SET NULL not valid;

alter table "public"."direct_messages" validate constraint "direct_messages_sender_device_id_fkey";

alter table "public"."messages" add constraint "messages_sender_device_id_fkey" FOREIGN KEY (sender_device_id) REFERENCES public.user_devices(id) ON DELETE SET NULL not valid;

alter table "public"."messages" validate constraint "messages_sender_device_id_fkey";

alter table "public"."mls_channel_state_snapshots" add constraint "mls_channel_state_snapshots_channel_id_fkey" FOREIGN KEY (channel_id) REFERENCES public.channels(id) ON DELETE CASCADE not valid;

alter table "public"."mls_channel_state_snapshots" validate constraint "mls_channel_state_snapshots_channel_id_fkey";

alter table "public"."mls_channel_state_snapshots" add constraint "mls_channel_state_snapshots_channel_unique" UNIQUE using index "mls_channel_state_snapshots_channel_unique";

alter table "public"."mls_channel_state_snapshots" add constraint "mls_channel_state_snapshots_group_unique" UNIQUE using index "mls_channel_state_snapshots_group_unique";

alter table "public"."mls_channel_state_snapshots" add constraint "mls_channel_state_snapshots_mls_group_id_fkey" FOREIGN KEY (mls_group_id) REFERENCES public.mls_groups(id) ON DELETE CASCADE not valid;

alter table "public"."mls_channel_state_snapshots" validate constraint "mls_channel_state_snapshots_mls_group_id_fkey";

alter table "public"."mls_channel_state_snapshots" add constraint "mls_channel_state_snapshots_server_id_fkey" FOREIGN KEY (server_id) REFERENCES public.servers(id) ON DELETE CASCADE not valid;

alter table "public"."mls_channel_state_snapshots" validate constraint "mls_channel_state_snapshots_server_id_fkey";

alter table "public"."mls_channel_state_snapshots" add constraint "mls_channel_state_snapshots_updated_by_device_id_fkey" FOREIGN KEY (updated_by_device_id) REFERENCES public.user_devices(id) ON DELETE SET NULL not valid;

alter table "public"."mls_channel_state_snapshots" validate constraint "mls_channel_state_snapshots_updated_by_device_id_fkey";

alter table "public"."mls_channel_state_snapshots" add constraint "mls_channel_state_snapshots_updated_by_user_id_fkey" FOREIGN KEY (updated_by_user_id) REFERENCES auth.users(id) ON DELETE SET NULL not valid;

alter table "public"."mls_channel_state_snapshots" validate constraint "mls_channel_state_snapshots_updated_by_user_id_fkey";

alter table "public"."post_comment_votes" add constraint "post_comment_votes_comment_id_fkey" FOREIGN KEY (comment_id) REFERENCES public.post_comments(id) ON DELETE CASCADE not valid;

alter table "public"."post_comment_votes" validate constraint "post_comment_votes_comment_id_fkey";

alter table "public"."post_comment_votes" add constraint "post_comment_votes_comment_id_user_id_key" UNIQUE using index "post_comment_votes_comment_id_user_id_key";

alter table "public"."post_comment_votes" add constraint "post_comment_votes_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."post_comment_votes" validate constraint "post_comment_votes_user_id_fkey";

alter table "public"."post_comment_votes" add constraint "post_comment_votes_vote_type_check" CHECK ((vote_type = ANY (ARRAY['up'::text, 'down'::text]))) not valid;

alter table "public"."post_comment_votes" validate constraint "post_comment_votes_vote_type_check";

alter table "public"."user_settings" add constraint "user_settings_dm_privacy_check" CHECK ((dm_privacy = ANY (ARRAY['everyone'::text, 'friends_only'::text]))) not valid;

alter table "public"."user_settings" validate constraint "user_settings_dm_privacy_check";

alter table "public"."user_settings" add constraint "user_settings_presence_check" CHECK ((presence = ANY (ARRAY['online'::text, 'idle'::text, 'dnd'::text, 'invisible'::text]))) not valid;

alter table "public"."user_settings" validate constraint "user_settings_presence_check";

alter table "public"."user_settings" add constraint "user_settings_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(auth_id) ON DELETE CASCADE not valid;

alter table "public"."user_settings" validate constraint "user_settings_user_id_fkey";

alter table "public"."user_settings" add constraint "user_settings_user_id_key" UNIQUE using index "user_settings_user_id_key";

alter table "public"."channels" add constraint "channels_tier_id_fkey" FOREIGN KEY (tier_id) REFERENCES public.subscription_tiers(id) ON DELETE CASCADE not valid;

alter table "public"."channels" validate constraint "channels_tier_id_fkey";

alter table "public"."direct_messages" add constraint "direct_messages_recipient_id_fkey" FOREIGN KEY (recipient_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."direct_messages" validate constraint "direct_messages_recipient_id_fkey";

alter table "public"."direct_messages" add constraint "direct_messages_sender_id_fkey" FOREIGN KEY (sender_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."direct_messages" validate constraint "direct_messages_sender_id_fkey";

alter table "public"."messages" add constraint "messages_sender_id_fkey" FOREIGN KEY (sender_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."messages" validate constraint "messages_sender_id_fkey";

alter table "public"."server_members" add constraint "server_members_role_id_fkey" FOREIGN KEY (role_id) REFERENCES public.server_roles(id) ON DELETE CASCADE not valid;

alter table "public"."server_members" validate constraint "server_members_role_id_fkey";

alter table "public"."server_members" add constraint "server_members_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(auth_id) ON DELETE CASCADE not valid;

alter table "public"."server_members" validate constraint "server_members_user_id_fkey";

alter table "public"."server_nicknames" add constraint "server_nicknames_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(auth_id) ON DELETE CASCADE not valid;

alter table "public"."server_nicknames" validate constraint "server_nicknames_user_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.assign_owner_admin()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  admin_role_id BIGINT;
BEGIN
  SELECT id INTO admin_role_id FROM server_roles
  WHERE server_id = NEW.id AND name = 'Admin' LIMIT 1;

  INSERT INTO server_members (server_id, user_id, role, role_id)
  VALUES (NEW.id, NEW.owner_id, 'admin', admin_role_id)
  ON CONFLICT DO NOTHING;

  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.check_channel_server_membership(p_server_id bigint, p_user_id uuid)
 RETURNS boolean
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (
    select 1
    from public.server_members
    where server_id = p_server_id
      and user_id = p_user_id
  );
$function$
;

CREATE OR REPLACE FUNCTION public.check_mls_membership(p_group_id bigint, p_user_id uuid)
 RETURNS boolean
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT EXISTS (
    SELECT 1
    FROM mls_group_members
    WHERE mls_group_id = p_group_id
      AND user_id = p_user_id
      AND membership_status = 'active'
  );
$function$
;

CREATE OR REPLACE FUNCTION public.check_server_membership(p_server_id bigint, p_user_id uuid)
 RETURNS boolean
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (
    select 1
    from public.server_members
    where server_id = p_server_id
      and user_id = p_user_id
  );
$function$
;

CREATE OR REPLACE FUNCTION public.create_default_roles()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  -- Admin role
  INSERT INTO server_roles (server_id, name, color, permissions, position, is_default)
  VALUES (NEW.id, 'Admin', '#FF6B00', '{"manage_channels": true, "manage_roles": true, "manage_server": true, "kick_members": true, "ban_members": true, "manage_messages": true}', 100, false);

  -- Moderator role
  INSERT INTO server_roles (server_id, name, color, permissions, position, is_default)
  VALUES (NEW.id, 'Moderator', '#00CC66', '{"manage_channels": false, "manage_roles": false, "manage_server": false, "kick_members": true, "ban_members": false, "manage_messages": true}', 50, false);

  -- Member role (default)
  INSERT INTO server_roles (server_id, name, color, permissions, position, is_default)
  VALUES (NEW.id, 'Member', '#999999', '{"manage_channels": false, "manage_roles": false, "manage_server": false, "kick_members": false, "ban_members": false, "manage_messages": false}', 0, true);

  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  INSERT INTO public.users (
    auth_id,
    email,
    username,
    display_name,
    age_range,
    nsfw_enabled
  )
  VALUES (
    NEW.id,
    NEW.email,
    NEW.raw_user_meta_data ->> 'username',
    NEW.raw_user_meta_data ->> 'display_name',
    CASE
      WHEN (NEW.raw_user_meta_data ->> 'age_range') IN ('under_13', '13_17', '18_plus')
      THEN (NEW.raw_user_meta_data ->> 'age_range')::age_range_type
      ELSE NULL
    END,
    false
  )
  ON CONFLICT (auth_id) DO NOTHING;
  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.is_blocked(sender uuid, recipient uuid)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM friendships
    WHERE status = 'blocked'
    AND (
      (requester_id = sender AND recipient_id = recipient)
      OR (requester_id = recipient AND recipient_id = sender)
    )
  );
END;
$function$
;

create or replace view "public"."post_comment_vote_totals" as  SELECT c.id AS comment_id,
    (COALESCE(sum(
        CASE
            WHEN (v.vote_type = 'up'::text) THEN 1
            ELSE 0
        END), (0)::bigint))::integer AS upvotes,
    (COALESCE(sum(
        CASE
            WHEN (v.vote_type = 'down'::text) THEN 1
            ELSE 0
        END), (0)::bigint))::integer AS downvotes
   FROM (public.post_comments c
     LEFT JOIN public.post_comment_votes v ON ((v.comment_id = c.id)))
  GROUP BY c.id;


CREATE OR REPLACE FUNCTION public.claim_prekey_bundle(p_target_user_id uuid, p_target_device_id text DEFAULT NULL::text)
 RETURNS TABLE(user_device_pk bigint, device_id text, registration_id integer, identity_public_key text, signed_prekey_id integer, signed_prekey_public_key text, signed_prekey_signature text, kyber_prekey_id integer, kyber_prekey_public_key text, kyber_prekey_signature text, one_time_prekey_id integer, one_time_prekey_public_key text)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  return query
  with target_device as (
    select
      ud.id as user_device_pk,
      ud.device_id,
      db.registration_id,
      db.identity_public_key,
      db.signed_prekey_id,
      db.signed_prekey_public_key,
      db.signed_prekey_signature,
      db.kyber_prekey_id,
      db.kyber_prekey_public_key,
      db.kyber_prekey_signature
    from public.user_devices ud
    join public.device_bundles db
      on db.user_device_id = ud.id
    where ud.user_id = p_target_user_id
      and ud.is_active = true
      and (p_target_device_id is null or ud.device_id = p_target_device_id)
    order by ud.created_at asc
    limit 1
  ),
  claimed_prekey as (
    update public.device_one_time_prekeys otp
    set
      is_consumed = true,
      consumed_at = timezone('utc', now()),
      claimed_by_user_id = auth.uid()
    where otp.id = (
      select otp2.id
      from public.device_one_time_prekeys otp2
      join target_device td
        on td.user_device_pk = otp2.user_device_id
      where otp2.is_consumed = false
      order by otp2.id asc
      limit 1
    )
    returning otp.user_device_id, otp.key_id, otp.public_key
  )
  select
    td.user_device_pk,
    td.device_id,
    td.registration_id,
    td.identity_public_key,
    td.signed_prekey_id,
    td.signed_prekey_public_key,
    td.signed_prekey_signature,
    td.kyber_prekey_id,
    td.kyber_prekey_public_key,
    td.kyber_prekey_signature,
    cp.key_id as one_time_prekey_id,
    cp.public_key as one_time_prekey_public_key
  from target_device td
  join claimed_prekey cp
    on cp.user_device_id = td.user_device_pk;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.create_default_server_roles_and_owner_membership()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
declare
  owner_role_id bigint;
begin
  insert into public.server_roles (server_id, name, color, permissions, position, is_default)
  values
    (
      new.id,
      'Owner',
      '#F0B232',
      '{"manage_channels": true, "manage_roles": true, "manage_server": true, "kick_members": true, "ban_members": true, "manage_messages": true}',
      400,
      true
    ),
    (
      new.id,
      'Admin',
      '#FF6B00',
      '{"manage_channels": true, "manage_roles": true, "manage_server": true, "kick_members": true, "ban_members": true, "manage_messages": true}',
      300,
      true
    ),
    (
      new.id,
      'Mod',
      '#00CC66',
      '{"manage_channels": false, "manage_roles": false, "manage_server": false, "kick_members": true, "ban_members": false, "manage_messages": true}',
      200,
      true
    ),
    (
      new.id,
      'Member',
      '#999999',
      '{"manage_channels": false, "manage_roles": false, "manage_server": false, "kick_members": false, "ban_members": false, "manage_messages": false}',
      100,
      true
    );

  select sr.id
    into owner_role_id
  from public.server_roles sr
  where sr.server_id = new.id
    and lower(sr.name) = 'owner'
  order by sr.position desc, sr.id asc
  limit 1;

  insert into public.server_members (server_id, user_id, role, role_id)
  values (new.id, new.owner_id, 'owner', owner_role_id)
  on conflict (server_id, user_id)
  do update
    set role = 'owner',
        role_id = excluded.role_id;

  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.delete_my_account()
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'auth'
AS $function$
declare
  current_user_id uuid := auth.uid();
  status jsonb;
  blocking_count integer;
begin
  if current_user_id is null then
    raise exception 'Not authenticated';
  end if;

  status := public.get_my_account_deletion_status();
  blocking_count := coalesce(jsonb_array_length(status->'blocking_servers'), 0);

  if blocking_count > 0 then
    raise exception 'Delete blocked. Add another owner or delete these servers first: %',
      (
        select string_agg(value->>'name', ', ')
        from jsonb_array_elements(status->'blocking_servers')
      );
  end if;

  update public.servers
  set owner_id = null
  where owner_id = current_user_id;

  delete from public.server_nicknames
  where user_id = current_user_id;

  delete from public.server_members
  where user_id = current_user_id;

  delete from storage.objects
  where owner_id = current_user_id::text
    and bucket_id = 'avatars';

  delete from auth.users
  where id = current_user_id;

  return jsonb_build_object(
    'deleted', true,
    'transferred_servers', 0
  );
end;
$function$
;

CREATE OR REPLACE FUNCTION public.get_dm_unread_counts()
 RETURNS TABLE(other_user_id uuid, unread_count bigint)
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT
    dm.sender_id AS other_user_id,
    COUNT(*)::BIGINT AS unread_count
  FROM direct_messages dm
  LEFT JOIN dm_read_state drs
    ON drs.other_user_id = dm.sender_id
    AND drs.user_id = auth.uid()
  WHERE
    dm.recipient_id = auth.uid()
    AND (drs.last_read_at IS NULL OR dm.created_at > drs.last_read_at)
  GROUP BY dm.sender_id
  HAVING COUNT(*) > 0;
$function$
;

CREATE OR REPLACE FUNCTION public.get_my_account_deletion_status()
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'auth'
AS $function$
declare
  current_user_id uuid := auth.uid();
  blocking_servers jsonb := '[]'::jsonb;
begin
  if current_user_id is null then
    raise exception 'Not authenticated';
  end if;

  with owned_servers as (
    select distinct
      s.id,
      coalesce(s.display_name, s.handle, 'Untitled Server') as name
    from public.server_members sm
    join public.servers s
      on s.id = sm.server_id
    where sm.user_id = current_user_id
      and lower(coalesce(sm.role, '')) = 'owner'
  )
  select coalesce(
    (
      select jsonb_agg(
        jsonb_build_object(
          'server_id', os.id,
          'name', os.name
        )
        order by os.name
      )
      from owned_servers os
      where not exists (
        select 1
        from public.server_members sm
        where sm.server_id = os.id
          and sm.user_id <> current_user_id
          and lower(coalesce(sm.role, '')) = 'owner'
      )
    ),
    '[]'::jsonb
  )
  into blocking_servers;

  return jsonb_build_object(
    'blocking_servers', blocking_servers,
    'transferable_servers', '[]'::jsonb
  );
end;
$function$
;

CREATE OR REPLACE FUNCTION public.get_unread_counts(p_channel_ids text[])
 RETURNS TABLE(channel_id text, unread_count bigint)
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT
    m.channel_id::TEXT,
    COUNT(*)::BIGINT AS unread_count
  FROM messages m
  LEFT JOIN channel_read_state crs
    ON crs.channel_id = m.channel_id::TEXT
    AND crs.user_id = auth.uid()
  WHERE
    m.channel_id::TEXT = ANY(p_channel_ids)
    AND m.sender_id != auth.uid()
    AND (crs.last_read_at IS NULL OR m.created_at > crs.last_read_at)
  GROUP BY m.channel_id
  HAVING COUNT(*) > 0;
$function$
;

CREATE OR REPLACE FUNCTION public.guard_server_owner_membership()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
declare
  owner_count bigint;
begin
  if tg_op = 'DELETE' then
    if lower(coalesce(old.role, '')) = 'owner' then
      select count(*)
        into owner_count
      from public.server_members sm
      where sm.server_id = old.server_id
        and lower(coalesce(sm.role, '')) = 'owner';

      if owner_count <= 1 then
        raise exception 'Servers must have at least one owner';
      end if;
    end if;

    return old;
  end if;

  if tg_op = 'UPDATE' then
    if lower(coalesce(old.role, '')) = 'owner'
       and lower(coalesce(new.role, '')) <> 'owner' then
      select count(*)
        into owner_count
      from public.server_members sm
      where sm.server_id = old.server_id
        and lower(coalesce(sm.role, '')) = 'owner';

      if owner_count <= 1 then
        raise exception 'Servers must have at least one owner';
      end if;
    end if;

    return new;
  end if;

  return coalesce(new, old);
end;
$function$
;

CREATE OR REPLACE FUNCTION public.is_server_admin(p_server_id bigint)
 RETURNS boolean
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select public.is_server_owner(p_server_id) or exists (
    select 1
    from public.server_members sm
    where sm.server_id = p_server_id
      and sm.user_id = auth.uid()
      and lower(coalesce(sm.role, '')) = 'admin'
  );
$function$
;

CREATE OR REPLACE FUNCTION public.is_server_owner(p_server_id bigint)
 RETURNS boolean
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (
    select 1
    from public.server_members sm
    where sm.server_id = p_server_id
      and sm.user_id = auth.uid()
      and lower(coalesce(sm.role, '')) = 'owner'
  );
$function$
;

CREATE OR REPLACE FUNCTION public.protect_builtin_server_roles()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
begin
  if tg_op = 'DELETE' then
    if lower(coalesce(old.name, '')) in ('owner', 'member') then
      raise exception 'The % role cannot be deleted', old.name;
    end if;

    return old;
  end if;

  if tg_op = 'UPDATE' then
    if lower(coalesce(old.name, '')) = 'owner' then
      new.name := 'Owner';
      new.permissions := '{"manage_channels": true, "manage_roles": true, "manage_server": true, "kick_members": true, "ban_members": true, "manage_messages": true}'::jsonb;
      new.position := 400;
      new.is_default := true;
    elsif lower(coalesce(old.name, '')) = 'member' then
      new.name := 'Member';
      new.position := 100;
      new.is_default := true;
    end if;

    return new;
  end if;

  return coalesce(new, old);
end;
$function$
;

CREATE OR REPLACE FUNCTION public.set_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$function$
;

grant delete on table "public"."mls_channel_state_snapshots" to "anon";

grant insert on table "public"."mls_channel_state_snapshots" to "anon";

grant references on table "public"."mls_channel_state_snapshots" to "anon";

grant select on table "public"."mls_channel_state_snapshots" to "anon";

grant trigger on table "public"."mls_channel_state_snapshots" to "anon";

grant truncate on table "public"."mls_channel_state_snapshots" to "anon";

grant update on table "public"."mls_channel_state_snapshots" to "anon";

grant delete on table "public"."mls_channel_state_snapshots" to "authenticated";

grant insert on table "public"."mls_channel_state_snapshots" to "authenticated";

grant references on table "public"."mls_channel_state_snapshots" to "authenticated";

grant select on table "public"."mls_channel_state_snapshots" to "authenticated";

grant trigger on table "public"."mls_channel_state_snapshots" to "authenticated";

grant truncate on table "public"."mls_channel_state_snapshots" to "authenticated";

grant update on table "public"."mls_channel_state_snapshots" to "authenticated";

grant delete on table "public"."mls_channel_state_snapshots" to "service_role";

grant insert on table "public"."mls_channel_state_snapshots" to "service_role";

grant references on table "public"."mls_channel_state_snapshots" to "service_role";

grant select on table "public"."mls_channel_state_snapshots" to "service_role";

grant trigger on table "public"."mls_channel_state_snapshots" to "service_role";

grant truncate on table "public"."mls_channel_state_snapshots" to "service_role";

grant update on table "public"."mls_channel_state_snapshots" to "service_role";

grant delete on table "public"."post_comment_votes" to "anon";

grant insert on table "public"."post_comment_votes" to "anon";

grant references on table "public"."post_comment_votes" to "anon";

grant select on table "public"."post_comment_votes" to "anon";

grant trigger on table "public"."post_comment_votes" to "anon";

grant truncate on table "public"."post_comment_votes" to "anon";

grant update on table "public"."post_comment_votes" to "anon";

grant delete on table "public"."post_comment_votes" to "authenticated";

grant insert on table "public"."post_comment_votes" to "authenticated";

grant references on table "public"."post_comment_votes" to "authenticated";

grant select on table "public"."post_comment_votes" to "authenticated";

grant trigger on table "public"."post_comment_votes" to "authenticated";

grant truncate on table "public"."post_comment_votes" to "authenticated";

grant update on table "public"."post_comment_votes" to "authenticated";

grant delete on table "public"."post_comment_votes" to "service_role";

grant insert on table "public"."post_comment_votes" to "service_role";

grant references on table "public"."post_comment_votes" to "service_role";

grant select on table "public"."post_comment_votes" to "service_role";

grant trigger on table "public"."post_comment_votes" to "service_role";

grant truncate on table "public"."post_comment_votes" to "service_role";

grant update on table "public"."post_comment_votes" to "service_role";

grant delete on table "public"."user_settings" to "anon";

grant insert on table "public"."user_settings" to "anon";

grant references on table "public"."user_settings" to "anon";

grant select on table "public"."user_settings" to "anon";

grant trigger on table "public"."user_settings" to "anon";

grant truncate on table "public"."user_settings" to "anon";

grant update on table "public"."user_settings" to "anon";

grant delete on table "public"."user_settings" to "authenticated";

grant insert on table "public"."user_settings" to "authenticated";

grant references on table "public"."user_settings" to "authenticated";

grant select on table "public"."user_settings" to "authenticated";

grant trigger on table "public"."user_settings" to "authenticated";

grant truncate on table "public"."user_settings" to "authenticated";

grant update on table "public"."user_settings" to "authenticated";

grant delete on table "public"."user_settings" to "service_role";

grant insert on table "public"."user_settings" to "service_role";

grant references on table "public"."user_settings" to "service_role";

grant select on table "public"."user_settings" to "service_role";

grant trigger on table "public"."user_settings" to "service_role";

grant truncate on table "public"."user_settings" to "service_role";

grant update on table "public"."user_settings" to "service_role";


  create policy "Allow authenticated reads"
  on "public"."channels"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Allow authenticated users to insert channels"
  on "public"."channels"
  as permissive
  for insert
  to authenticated
with check ((auth.uid() = auth.uid()));



  create policy "Allow authenticated users to reach channels"
  on "public"."channels"
  as permissive
  for select
  to authenticated
using ((auth.uid() = auth.uid()));



  create policy "Allow server owners to delete channels"
  on "public"."channels"
  as permissive
  for delete
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.servers
  WHERE ((servers.id = channels.server_id) AND (servers.owner_id = auth.uid())))));



  create policy "Users can send DMs if not blocked"
  on "public"."direct_messages"
  as permissive
  for insert
  to public
with check (((auth.uid() = sender_id) AND (NOT public.is_blocked(auth.uid(), recipient_id))));



  create policy "Users can view their own DMs"
  on "public"."direct_messages"
  as permissive
  for select
  to public
using (((auth.uid() = sender_id) OR (auth.uid() = recipient_id)));



  create policy "Users can delete their own friendships"
  on "public"."friendships"
  as permissive
  for delete
  to public
using (((auth.uid() = requester_id) OR (auth.uid() = recipient_id)));



  create policy "Users can send friend requests"
  on "public"."friendships"
  as permissive
  for insert
  to public
with check ((auth.uid() = requester_id));



  create policy "Users can update friendships they received"
  on "public"."friendships"
  as permissive
  for update
  to public
using (((auth.uid() = recipient_id) OR (auth.uid() = requester_id)));



  create policy "Users can view their own friendships"
  on "public"."friendships"
  as permissive
  for select
  to public
using (((auth.uid() = requester_id) OR (auth.uid() = recipient_id)));



  create policy "Allow authenticated inserts on messages"
  on "public"."messages"
  as permissive
  for insert
  to authenticated
with check ((auth.uid() = sender_id));



  create policy "Allow authenticated reads on messages"
  on "public"."messages"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Allow users to delete their own messages"
  on "public"."messages"
  as permissive
  for delete
  to authenticated
using ((sender_id = auth.uid()));



  create policy "Server members can insert channel MLS snapshots"
  on "public"."mls_channel_state_snapshots"
  as permissive
  for insert
  to authenticated
with check ((public.check_channel_server_membership(server_id, auth.uid()) AND (updated_by_user_id = auth.uid()) AND (EXISTS ( SELECT 1
   FROM public.mls_groups g
  WHERE ((g.id = mls_channel_state_snapshots.mls_group_id) AND (g.channel_id = mls_channel_state_snapshots.channel_id) AND (g.server_id = mls_channel_state_snapshots.server_id) AND (g.group_identifier = mls_channel_state_snapshots.group_identifier) AND (g.conversation_kind = 'channel'::text))))));



  create policy "Server members can read channel MLS snapshots"
  on "public"."mls_channel_state_snapshots"
  as permissive
  for select
  to authenticated
using (public.check_channel_server_membership(server_id, auth.uid()));



  create policy "Server members can update channel MLS snapshots"
  on "public"."mls_channel_state_snapshots"
  as permissive
  for update
  to authenticated
using (public.check_channel_server_membership(server_id, auth.uid()))
with check ((public.check_channel_server_membership(server_id, auth.uid()) AND (updated_by_user_id = auth.uid()) AND (EXISTS ( SELECT 1
   FROM public.mls_groups g
  WHERE ((g.id = mls_channel_state_snapshots.mls_group_id) AND (g.channel_id = mls_channel_state_snapshots.channel_id) AND (g.server_id = mls_channel_state_snapshots.server_id) AND (g.group_identifier = mls_channel_state_snapshots.group_identifier) AND (g.conversation_kind = 'channel'::text))))));



  create policy "Users can insert MLS channel snapshots for their groups"
  on "public"."mls_channel_state_snapshots"
  as permissive
  for insert
  to authenticated
with check (((public.check_mls_group_membership(mls_group_id, auth.uid()) OR public.check_server_membership(server_id, auth.uid())) AND ((updated_by_device_id IS NULL) OR (EXISTS ( SELECT 1
   FROM public.user_devices ud
  WHERE ((ud.id = mls_channel_state_snapshots.updated_by_device_id) AND (ud.user_id = auth.uid()) AND (ud.is_active = true)))))));



  create policy "Users can read MLS channel snapshots for their groups"
  on "public"."mls_channel_state_snapshots"
  as permissive
  for select
  to authenticated
using ((public.check_mls_group_membership(mls_group_id, auth.uid()) OR public.check_server_membership(server_id, auth.uid())));



  create policy "Users can update MLS channel snapshots for their groups"
  on "public"."mls_channel_state_snapshots"
  as permissive
  for update
  to authenticated
using ((public.check_mls_group_membership(mls_group_id, auth.uid()) OR public.check_server_membership(server_id, auth.uid())))
with check (((public.check_mls_group_membership(mls_group_id, auth.uid()) OR public.check_server_membership(server_id, auth.uid())) AND ((updated_by_device_id IS NULL) OR (EXISTS ( SELECT 1
   FROM public.user_devices ud
  WHERE ((ud.id = mls_channel_state_snapshots.updated_by_device_id) AND (ud.user_id = auth.uid()) AND (ud.is_active = true)))))));



  create policy "Server members can read channel MLS commits"
  on "public"."mls_commits"
  as permissive
  for select
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.mls_groups g
  WHERE ((g.id = mls_commits.mls_group_id) AND (g.server_id IS NOT NULL) AND (g.conversation_kind = ANY (ARRAY['channel'::text, 'server_channel'::text])) AND public.check_channel_server_membership(g.server_id, auth.uid())))));



  create policy "Server members can read channel MLS groups"
  on "public"."mls_groups"
  as permissive
  for select
  to authenticated
using ((((conversation_kind = 'dm'::text) AND ((dm_user_a = auth.uid()) OR (dm_user_b = auth.uid()))) OR ((conversation_kind = 'channel'::text) AND (server_id IS NOT NULL) AND public.check_channel_server_membership(server_id, auth.uid())) OR ((conversation_kind = 'server_channel'::text) AND (server_id IS NOT NULL) AND public.check_channel_server_membership(server_id, auth.uid()))));



  create policy "post_comment_votes_delete"
  on "public"."post_comment_votes"
  as permissive
  for delete
  to public
using ((user_id = auth.uid()));



  create policy "post_comment_votes_insert"
  on "public"."post_comment_votes"
  as permissive
  for insert
  to public
with check ((user_id = auth.uid()));



  create policy "post_comment_votes_select"
  on "public"."post_comment_votes"
  as permissive
  for select
  to public
using (true);



  create policy "post_comment_votes_update"
  on "public"."post_comment_votes"
  as permissive
  for update
  to public
using ((user_id = auth.uid()));



  create policy "reports_insert_own"
  on "public"."reports"
  as permissive
  for insert
  to authenticated
with check ((reporter_id = auth.uid()));



  create policy "Allow members to leave servers"
  on "public"."server_members"
  as permissive
  for delete
  to authenticated
using ((user_id = auth.uid()));



  create policy "Allow owners to remove members"
  on "public"."server_members"
  as permissive
  for delete
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.servers
  WHERE ((servers.id = server_members.server_id) AND (servers.owner_id = auth.uid())))));



  create policy "Owners and admins can remove members"
  on "public"."server_members"
  as permissive
  for delete
  to authenticated
using ((public.is_server_owner(server_id) OR public.is_server_admin(server_id)));



  create policy "Owners can update member roles"
  on "public"."server_members"
  as permissive
  for update
  to authenticated
using (public.is_server_owner(server_id))
with check (public.is_server_owner(server_id));



  create policy "Users can view their own memberships"
  on "public"."server_members"
  as permissive
  for select
  to public
using ((user_id = auth.uid()));



  create policy "members can view server members"
  on "public"."server_members"
  as permissive
  for select
  to public
using (((user_id = auth.uid()) OR public.check_server_membership(server_id, auth.uid())));



  create policy "Anyone can view nicknames"
  on "public"."server_nicknames"
  as permissive
  for select
  to public
using (true);



  create policy "Users can delete their own nickname"
  on "public"."server_nicknames"
  as permissive
  for delete
  to public
using ((auth.uid() = user_id));



  create policy "Users can set their own nickname"
  on "public"."server_nicknames"
  as permissive
  for insert
  to public
with check ((auth.uid() = user_id));



  create policy "Users can update their own nickname"
  on "public"."server_nicknames"
  as permissive
  for update
  to public
using ((auth.uid() = user_id));



  create policy "Anyone can view server roles"
  on "public"."server_roles"
  as permissive
  for select
  to public
using (true);



  create policy "Server owner can manage roles"
  on "public"."server_roles"
  as permissive
  for all
  to public
using ((EXISTS ( SELECT 1
   FROM public.servers
  WHERE ((servers.id = server_roles.server_id) AND (servers.owner_id = auth.uid())))));



  create policy "Allow owners to delete their servers"
  on "public"."servers"
  as permissive
  for delete
  to authenticated
using ((auth.uid() = owner_id));



  create policy "Allow owners to update their servers"
  on "public"."servers"
  as permissive
  for update
  to authenticated
using ((auth.uid() = owner_id));



  create policy "Allow users to insert their own servers"
  on "public"."servers"
  as permissive
  for insert
  to authenticated
with check ((auth.uid() = owner_id));



  create policy "Anyone can view tiers"
  on "public"."subscription_tiers"
  as permissive
  for select
  to public
using (true);



  create policy "Server owner can manage tiers"
  on "public"."subscription_tiers"
  as permissive
  for all
  to public
using ((EXISTS ( SELECT 1
   FROM public.servers
  WHERE ((servers.id = subscription_tiers.server_id) AND (servers.owner_id = auth.uid())))));



  create policy "Users can update their own settings"
  on "public"."user_settings"
  as permissive
  for update
  to public
using ((auth.uid() = user_id));



  create policy "Users can view their own settings"
  on "public"."user_settings"
  as permissive
  for select
  to public
using ((auth.uid() = user_id));



  create policy "Users can insert their own profile"
  on "public"."users"
  as permissive
  for insert
  to authenticated
with check ((auth_id = auth.uid()));



  create policy "Users can read all profiles"
  on "public"."users"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Users can read profiles of people in shared servers"
  on "public"."users"
  as permissive
  for select
  to authenticated
using (((auth.uid() = auth_id) OR (EXISTS ( SELECT 1
   FROM (public.server_members mine
     JOIN public.server_members theirs ON ((theirs.server_id = mine.server_id)))
  WHERE ((mine.user_id = auth.uid()) AND (theirs.user_id = users.auth_id))))));



  create policy "Users can update their own profile"
  on "public"."users"
  as permissive
  for update
  to authenticated
using ((auth_id = auth.uid()));



  create policy "Users can insert MLS commits from their own devices"
  on "public"."mls_commits"
  as permissive
  for insert
  to authenticated
with check ((public.check_mls_membership(mls_group_id, auth.uid()) AND (EXISTS ( SELECT 1
   FROM public.user_devices ud
  WHERE ((ud.id = mls_commits.sender_device_id) AND (ud.user_id = auth.uid()))))));



  create policy "Users can read MLS commits for their groups"
  on "public"."mls_commits"
  as permissive
  for select
  to authenticated
using ((public.check_mls_group_membership(mls_group_id, auth.uid()) OR (EXISTS ( SELECT 1
   FROM public.mls_groups g
  WHERE ((g.id = mls_commits.mls_group_id) AND (g.conversation_kind = ANY (ARRAY['channel'::text, 'server_channel'::text])) AND (g.server_id IS NOT NULL) AND public.check_channel_server_membership(g.server_id, auth.uid()))))));



  create policy "Users can read MLS group members for their groups"
  on "public"."mls_group_members"
  as permissive
  for select
  to authenticated
using (((user_id = auth.uid()) OR public.check_mls_group_membership(mls_group_id, auth.uid()) OR (EXISTS ( SELECT 1
   FROM public.mls_groups g
  WHERE ((g.id = mls_group_members.mls_group_id) AND (g.conversation_kind = ANY (ARRAY['channel'::text, 'server_channel'::text])) AND (g.server_id IS NOT NULL) AND public.check_channel_server_membership(g.server_id, auth.uid()))))));



  create policy "Users can update MLS memberships in their groups"
  on "public"."mls_group_members"
  as permissive
  for update
  to authenticated
using (public.check_mls_membership(mls_group_id, auth.uid()));



  create policy "Group members can update MLS groups"
  on "public"."mls_groups"
  as permissive
  for update
  to authenticated
using ((public.check_mls_group_membership(id, auth.uid()) OR ((conversation_kind = ANY (ARRAY['channel'::text, 'server_channel'::text])) AND (server_id IS NOT NULL) AND public.check_server_membership(server_id, auth.uid()))))
with check ((public.check_mls_group_membership(id, auth.uid()) OR ((conversation_kind = ANY (ARRAY['channel'::text, 'server_channel'::text])) AND (server_id IS NOT NULL) AND public.check_server_membership(server_id, auth.uid()))));



  create policy "Users can read MLS groups they belong to"
  on "public"."mls_groups"
  as permissive
  for select
  to authenticated
using ((((conversation_kind = 'dm'::text) AND ((dm_user_a = auth.uid()) OR (dm_user_b = auth.uid()))) OR public.check_mls_group_membership(id, auth.uid()) OR ((conversation_kind = ANY (ARRAY['channel'::text, 'server_channel'::text])) AND (server_id IS NOT NULL) AND public.check_server_membership(server_id, auth.uid()))));



  create policy "Servers visible based on visibility"
  on "public"."servers"
  as permissive
  for select
  to authenticated
using (((visibility = 'public'::text) OR (auth.uid() = owner_id) OR (auth.uid() IN ( SELECT server_members.user_id
   FROM public.server_members
  WHERE (server_members.server_id = servers.id)))));


CREATE TRIGGER "send-message-notification" AFTER INSERT ON public.messages FOR EACH ROW EXECUTE FUNCTION supabase_functions.http_request('https://kltykhkcvdwhfjgvevbt.supabase.co/functions/v1/send-message-notification', 'POST', '{"Content-type":"application/json","x-webhooks-secret":"ac3f536fb3bf6808117194b4415e901f34cc98dfac2af9472a458f0e8431d4a9"}', '{}', '5000');

CREATE TRIGGER set_mls_channel_state_snapshots_updated_at BEFORE UPDATE ON public.mls_channel_state_snapshots FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


  create policy "Anyone can view avatars"
  on "storage"."objects"
  as permissive
  for select
  to public
using ((bucket_id = 'avatars'::text));



  create policy "Authenticated users can upload avatars"
  on "storage"."objects"
  as permissive
  for insert
  to public
with check (((bucket_id = 'avatars'::text) AND (auth.role() = 'authenticated'::text)));



  create policy "Avatars are publicly readable"
  on "storage"."objects"
  as permissive
  for select
  to public
using ((bucket_id = 'avatars'::text));



  create policy "Users can delete their own avatars"
  on "storage"."objects"
  as permissive
  for delete
  to public
using (((bucket_id = 'avatars'::text) AND (auth.role() = 'authenticated'::text)));



  create policy "Users can update their own avatar"
  on "storage"."objects"
  as permissive
  for update
  to authenticated
using (((bucket_id = 'avatars'::text) AND ((auth.uid())::text = (storage.foldername(name))[1])));



  create policy "Users can update their own avatars"
  on "storage"."objects"
  as permissive
  for update
  to public
using (((bucket_id = 'avatars'::text) AND (auth.role() = 'authenticated'::text)));



  create policy "Users can upload their own avatar"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check (((bucket_id = 'avatars'::text) AND ((auth.uid())::text = (storage.foldername(name))[1])));



