create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.user_devices (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  device_id text not null,
  label text,
  created_at timestamptz not null default timezone('utc', now()),
  last_seen_at timestamptz,
  is_active boolean not null default true,
  unique (user_id, device_id)
);

create index if not exists user_devices_user_id_idx
  on public.user_devices (user_id);

create index if not exists user_devices_user_id_is_active_idx
  on public.user_devices (user_id, is_active);

create table if not exists public.device_bundles (
  id bigint generated by default as identity primary key,
  user_device_id bigint not null unique references public.user_devices (id) on delete cascade,
  registration_id integer not null,
  identity_public_key text not null,
  signed_prekey_id integer not null,
  signed_prekey_public_key text not null,
  signed_prekey_signature text not null,
  kyber_prekey_id integer,
  kyber_prekey_public_key text,
  kyber_prekey_signature text,
  bundle_version integer not null default 1,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint device_bundles_kyber_fields_check check (
    (
      kyber_prekey_id is null
      and kyber_prekey_public_key is null
      and kyber_prekey_signature is null
    )
    or (
      kyber_prekey_id is not null
      and kyber_prekey_public_key is not null
      and kyber_prekey_signature is not null
    )
  )
);

create trigger set_device_bundles_updated_at
before update on public.device_bundles
for each row
execute function public.set_updated_at();

create table if not exists public.device_one_time_prekeys (
  id bigint generated by default as identity primary key,
  user_device_id bigint not null references public.user_devices (id) on delete cascade,
  key_id integer not null,
  public_key text not null,
  is_consumed boolean not null default false,
  consumed_at timestamptz,
  claimed_by_user_id uuid references auth.users (id) on delete set null,
  claimed_by_device_id bigint references public.user_devices (id) on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  unique (user_device_id, key_id),
  constraint consumed_prekey_requires_timestamp check (
    (is_consumed = false and consumed_at is null)
    or (is_consumed = true and consumed_at is not null)
  )
);

create index if not exists device_one_time_prekeys_available_idx
  on public.device_one_time_prekeys (user_device_id, id)
  where is_consumed = false;

create table if not exists public.direct_message_device_envelopes (
  id bigint generated by default as identity primary key,
  client_message_id uuid not null,
  sender_user_id uuid not null references auth.users (id) on delete cascade,
  sender_device_pk bigint not null references public.user_devices (id) on delete cascade,
  recipient_user_id uuid not null references auth.users (id) on delete cascade,
  recipient_device_pk bigint not null references public.user_devices (id) on delete cascade,
  ciphertext_type smallint not null,
  ciphertext_body text not null,
  created_at timestamptz not null default timezone('utc', now()),
  delivered_at timestamptz,
  read_at timestamptz,
  constraint direct_message_device_envelopes_ciphertext_type_check
    check (ciphertext_type in (1, 2)),
  constraint direct_message_device_envelopes_unique_delivery
    unique (client_message_id, recipient_device_pk)
);

create index if not exists direct_message_device_envelopes_recipient_idx
  on public.direct_message_device_envelopes (recipient_user_id, recipient_device_pk, created_at);

create index if not exists direct_message_device_envelopes_sender_idx
  on public.direct_message_device_envelopes (sender_user_id, sender_device_pk, created_at);
