-- Device management for MLS devices and browser sessions.
-- Primary devices are long-lived app installs (desktop now, mobile later).
-- Web logins are secondary devices whose local keys follow browser storage rules.

alter table public.user_devices
  add column if not exists device_role text not null default 'secondary',
  add column if not exists parent_device_id bigint references public.user_devices(id) on delete set null,
  add column if not exists storage_scope text not null default 'browser_session',
  add column if not exists last_user_agent text,
  add column if not exists revoked_at timestamptz,
  add column if not exists blacklisted_at timestamptz,
  add column if not exists hidden_at timestamptz,
  add column if not exists revoked_by_device_id bigint references public.user_devices(id) on delete set null;

alter table public.user_devices
  drop constraint if exists user_devices_device_role_check;

alter table public.user_devices
  add constraint user_devices_device_role_check
  check (device_role in ('primary', 'secondary'));

alter table public.user_devices
  drop constraint if exists user_devices_storage_scope_check;

alter table public.user_devices
  add constraint user_devices_storage_scope_check
  check (storage_scope in ('persistent', 'browser_session'));

update public.user_devices
set
  device_role = case
    when device_id like 'desktop-%'
      or device_id like 'windows-%'
      or device_id like 'macos-%'
      or device_id like 'linux-%'
      or device_id like 'ios-%'
      or device_id like 'android-%'
      then 'primary'
    else 'secondary'
  end,
  storage_scope = case
    when device_id like 'web-%' then 'browser_session'
    else 'persistent'
  end
where true;

create index if not exists user_devices_user_role_active_idx
  on public.user_devices (user_id, device_role, is_active)
  where revoked_at is null;

create table if not exists public.user_device_key_derivations (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  primary_device_id bigint not null references public.user_devices(id) on delete cascade,
  secondary_device_id bigint not null references public.user_devices(id) on delete cascade,
  grant_scope text not null default 'message_history',
  wrapped_secondary_key text,
  created_at timestamptz not null default timezone('utc', now()),
  revoked_at timestamptz,
  unique (secondary_device_id),
  constraint user_device_key_derivations_scope_check
    check (grant_scope in ('message_history'))
);

alter table public.user_device_key_derivations enable row level security;

drop policy if exists "Users can read their own device key derivations"
on public.user_device_key_derivations;

create policy "Users can read their own device key derivations"
on public.user_device_key_derivations
for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "Users can create their own device key derivations"
on public.user_device_key_derivations;

create policy "Users can create their own device key derivations"
on public.user_device_key_derivations
for insert
to authenticated
with check (
  user_id = auth.uid()
  and exists (
    select 1
    from public.user_devices primary_device
    where primary_device.id = primary_device_id
      and primary_device.user_id = auth.uid()
      and primary_device.device_role = 'primary'
      and primary_device.is_active = true
      and primary_device.revoked_at is null
  )
  and exists (
    select 1
    from public.user_devices secondary_device
    where secondary_device.id = secondary_device_id
      and secondary_device.user_id = auth.uid()
      and secondary_device.device_role = 'secondary'
      and secondary_device.is_active = true
      and secondary_device.revoked_at is null
  )
);

drop policy if exists "Users can update their own device key derivations"
on public.user_device_key_derivations;

create policy "Users can update their own device key derivations"
on public.user_device_key_derivations
for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop function if exists public.get_my_devices();

create or replace function public.get_my_devices()
returns table (
  id bigint,
  device_id text,
  label text,
  device_role text,
  parent_device_id bigint,
  storage_scope text,
  created_at timestamptz,
  last_seen_at timestamptz,
  last_user_agent text,
  is_active boolean,
  revoked_at timestamptz,
  blacklisted_at timestamptz,
  available_key_packages bigint,
  active_group_memberships bigint
)
language sql
security definer
set search_path = public
as $$
  select
    ud.id,
    ud.device_id,
    ud.label,
    ud.device_role,
    ud.parent_device_id,
    ud.storage_scope,
    ud.created_at,
    ud.last_seen_at,
    ud.last_user_agent,
    ud.is_active,
    ud.revoked_at,
    ud.blacklisted_at,
    (
      select count(*)
      from public.mls_key_packages mkp
      where mkp.user_device_id = ud.id
        and mkp.is_consumed = false
    ) as available_key_packages,
    (
      select count(*)
      from public.mls_group_members mgm
      where mgm.user_device_id = ud.id
        and mgm.membership_status = 'active'
    ) as active_group_memberships
  from public.user_devices ud
  where ud.user_id = auth.uid()
    and ud.hidden_at is null
  order by
    ud.is_active desc,
    ud.revoked_at desc nulls first,
    ud.last_seen_at desc nulls last,
    ud.created_at desc;
$$;

create or replace function public.revoke_my_device(p_user_device_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  target_record public.user_devices%rowtype;
begin
  select *
    into target_record
  from public.user_devices ud
  where ud.id = p_user_device_id;

  if target_record.user_id is distinct from auth.uid() then
    raise exception 'Device not found';
  end if;

  update public.user_devices
  set
    is_active = false,
    revoked_at = coalesce(revoked_at, timezone('utc', now()))
  where id = p_user_device_id
    and user_id = auth.uid();

  update public.mls_key_packages
  set
    is_consumed = true,
    consumed_at = coalesce(consumed_at, timezone('utc', now()))
  where user_device_id = p_user_device_id
    and is_consumed = false;

  update public.user_device_key_derivations
  set revoked_at = coalesce(revoked_at, timezone('utc', now()))
  where user_id = auth.uid()
    and (primary_device_id = p_user_device_id or secondary_device_id = p_user_device_id)
    and revoked_at is null;
end;
$$;

create or replace function public.delete_my_revoked_device(p_user_device_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  target_record public.user_devices%rowtype;
begin
  select *
    into target_record
  from public.user_devices ud
  where ud.id = p_user_device_id;

  if target_record.user_id is distinct from auth.uid() then
    raise exception 'Device not found';
  end if;

  if target_record.is_active = true and target_record.revoked_at is null then
    raise exception 'Only revoked devices can be deleted';
  end if;

  update public.user_devices
  set hidden_at = coalesce(hidden_at, timezone('utc', now()))
  where id = p_user_device_id
    and user_id = auth.uid();
end;
$$;

create or replace function public.reactivate_my_device(p_user_device_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  target_record public.user_devices%rowtype;
begin
  select *
    into target_record
  from public.user_devices ud
  where ud.id = p_user_device_id;

  if target_record.user_id is distinct from auth.uid() then
    raise exception 'Device not found';
  end if;

  update public.user_devices
  set
    is_active = true,
    revoked_at = null,
    blacklisted_at = null,
    hidden_at = null,
    last_seen_at = timezone('utc', now())
  where id = p_user_device_id
    and user_id = auth.uid();
end;
$$;

create or replace function public.blacklist_my_device(p_user_device_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  target_record public.user_devices%rowtype;
begin
  select *
    into target_record
  from public.user_devices ud
  where ud.id = p_user_device_id;

  if target_record.user_id is distinct from auth.uid() then
    raise exception 'Device not found';
  end if;

  update public.user_devices
  set
    is_active = false,
    revoked_at = coalesce(revoked_at, timezone('utc', now())),
    blacklisted_at = coalesce(blacklisted_at, timezone('utc', now()))
  where id = p_user_device_id
    and user_id = auth.uid();

  update public.mls_key_packages
  set
    is_consumed = true,
    consumed_at = coalesce(consumed_at, timezone('utc', now()))
  where user_device_id = p_user_device_id
    and is_consumed = false;

  update public.user_device_key_derivations
  set revoked_at = coalesce(revoked_at, timezone('utc', now()))
  where user_id = auth.uid()
    and (primary_device_id = p_user_device_id or secondary_device_id = p_user_device_id)
    and revoked_at is null;
end;
$$;

grant execute on function public.get_my_devices() to authenticated;
grant execute on function public.revoke_my_device(bigint) to authenticated;
grant execute on function public.reactivate_my_device(bigint) to authenticated;
grant execute on function public.blacklist_my_device(bigint) to authenticated;
grant execute on function public.delete_my_revoked_device(bigint) to authenticated;

grant select, insert, update on table public.user_device_key_derivations to authenticated;
grant select, insert, update on table public.user_device_key_derivations to service_role;
grant usage, select on sequence public.user_device_key_derivations_id_seq to authenticated;
grant usage, select on sequence public.user_device_key_derivations_id_seq to service_role;
